# Generated by Django 4.2.2 on 2023-06-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='address',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
